---
- name: Malware check 
  hosts: all
  gather_facts: no
  vars:
    finspy_script: /var/tmp/finspy.sh
    backdoor_file: /var/tmp/linux_generic_match

  tasks:
  - name: Ensure EPEL is enabled
    tags: pre-flight 
    yum: 
      name: epel-release 
      state: present 

  - name: Install yara and wget
    tags: pre-flight
    yum:
      name: 
        - yara
        - wget
      state: present

  - name: Download finspy script
    tags: finspy
    get_url:
      url: https://raw.githubusercontent.com/boogiespook/malware-playbooks/main/finspy.sh
      dest: '{{ finspy_script }}'
      mode: '0755'

  - name: Run the finspy script in the background
    tags: finspy
    ansible.builtin.command: "{{ finspy_script }} &"
    async: 240
    poll: 0

  - name: Get PID of finspy
    tags: finspy
    ansible.builtin.shell: pgrep -f "/bin/bash {{ finspy_script }}"
    register: finspy_pid

  - name: Get Linux_Backdoor file
    tags: backdoor
    get_url:
      url: https://raw.githubusercontent.com/boogiespook/malware-playbooks/main/linux_generic_match.base64
      dest: '{{ backdoor_file }}'
      mode: '0755'

  - name: Decode the base64 backdoor file
    tags: backdoor
    shell: base64 -d {{ backdoor_file }} > {{ backdoor_file }}.decoded

  - name: Run Insights malware check
    tags: run_insights
    ansible.builtin.shell: /usr/bin/insights-client --collector malware-detection

  - name: Kill finspy
    tags: finspy
    ansible.builtin.shell: kill -9 {{ finspy_pid.stdout }}

  - name: Remove finspy script
    tags: finspy
    ansible.builtin.file:
      path: "{{ finspy_script }}"
      state: absent

  - name: Remove backdoor files
    tags: backdoor
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ backdoor_file }}" 
      - "{{ backdoor_file }}.decoded"

