---
- name: Malware check 
  hosts: all
  gather_facts: no
  become: yes
  vars:
    finspy_script: /var/tmp/finspy.sh
    backdoor_file: /var/tmp/linux_generic_match
    eicar_files:
      - https://secure.eicar.org/eicar.com
      - https://secure.eicar.org/eicar.com.txt
      - https://secure.eicar.org/eicar_com.zip
      - https://secure.eicar.org/eicarcom2.zip

  tasks:
  - name: Install yara and wget
    tags: pre-flight
    yum:
      name: 
        - yara
        - wget
      state: present

  - name: Check if malware-detection default config exists
    tags: pre-flight
    ansible.builtin.stat:
      path: /etc/insights-client/malware-detection-config.yml
    register: malware_config

  - name: Run Insights malware test check to generate default config
    tags: pre-flight
    ansible.builtin.shell: /usr/bin/insights-client --collector malware-detection
    when: not malware_config.stat.exists

  - name: Ensure that malware scanner is not configured in test mode
    tags: pre-flight
    lineinfile:
      path: /etc/insights-client/malware-detection-config.yml
      regexp: '^test_scan'
      line: "test_scan: true"
      backup: yes

  - name: Download finspy script
    tags: 
      - finspy
      - test_malware
    get_url:
      url: https://raw.githubusercontent.com/boogiespook/malware-playbooks/main/finspy.sh
      dest: '{{ finspy_script }}'
      mode: '0755'

  - name: Run the finspy script in the background
    tags:
      - finspy
      - test_malware
    ansible.builtin.command: "{{ finspy_script }} &"
    async: 240
    poll: 0

  - name: Get PID of finspy
    tags:
      - finspy
      - test_malware
    ansible.builtin.shell: pgrep -f "/bin/bash {{ finspy_script }}"
    register: finspy_pid

  - name: Get Linux_Backdoor file
    tags:
      - backdoor
      - test_malware
    get_url:
      url: https://raw.githubusercontent.com/boogiespook/malware-playbooks/main/linux_generic_match.base64
      dest: '{{ backdoor_file }}'
      mode: '0755'

  - name: Decode the base64 backdoor file
    tags:
      - backdoor
      - test_malware
    shell: base64 -d {{ backdoor_file }} > {{ backdoor_file }}.decoded

  - name: Download the eicar malware test files
    tags:
      - eicar
      - test_malware
    get_url:
      url: "{{ item }}"
      dest: /var/tmp/
      mode: '0644'
    loop: "{{ eicar_files }}"

  - name: Run Insights malware check
    tags: run_insights
    ansible.builtin.shell: /usr/bin/insights-client --collector malware-detection

  - name: Kill finspy
    tags:
      - finspy
      - test_malware
    ansible.builtin.shell: kill -9 {{ finspy_pid.stdout }}

  - name: Remove finspy script
    tags:
      - finspy
      - test_malware
    ansible.builtin.file:
      path: "{{ finspy_script }}"
      state: absent

  - name: Remove backdoor files
    tags:
      - backdoor1
      - test_malware
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ backdoor_file }}" 
      - "{{ backdoor_file }}.decoded"

  - name: Remove eicar files
    tags:
      - eicar
      - test_malware
    ansible.builtin.file:
      path: "/var/tmp/{{ item }}"
      state: absent
    loop: "{{ eicar_files }}"