---
- name: Malware check 
  hosts: rhel
  gather_facts: no
  vars:
    finspy_script: /var/tmp/finspy.sh

  tasks:
  - name: Ensure EPEL is enabled
    tags: pre-flight 
    yum: 
      name: epel-release 
      state: present 

  - name: Install yara
    tags: pre-flight
    yum:
      name: yara
      state: present

  - name: Install wget package 
    tags: pre-flight
    yum:
      name: wget
      state: installed

  - name: Download finspy script
    tags: finspy
    get_url:
      url: https://raw.githubusercontent.com/boogiespook/malware-playbooks/main/finspy.sh
      dest: '{{ finspy_script }}'
      mode: '0755'

  - name: Run the finspy script in the background
    tags: finspy
    ansible.builtin.command: "{{ finspy_script }} &"
    async: 240
    poll: 0

  - name: Get PID of finspy
    tags: finspy
    ansible.builtin.shell: pgrep -f "/bin/bash {{ finspy_script }}"
    register: finspy_pid

  - name: Run Insights malware check
    tags: run_insights
    ansible.builtin.shell: /usr/bin/insights-client --collector malware-detection

  - name: Kill finspy
    tags: finspy
    ansible.builtin.shell: kill -9 {{ finspy_pid.stdout }}

  - name: Remove finspy script
    tags: finspy
    ansible.builtin.file:
      path: "{{ finspy_script }}"
      state: absent

